In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset = pd.read_csv('train.csv')
X = dataset.iloc[ : , :-1].values
y = dataset.iloc[ : , -1].values
test_set = pd.read_csv('test.csv')

In [3]:
dataset.head(10)

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1
5           1859     0          0.5  ...             0     0            1
6           1821     0          1.7  ...             0     1            3
7           1954     0          0.5  ...             1     1            0
8           1445     1          0.5  ...             0     0            0
9            509     1          0.6  ...             0     0            0

[10 rows x 21 columns]

In [4]:
dataset.describe()

battery_power       blue  ...         wifi  price_range
count    2000.000000  2000.0000  ...  2000.000000  2000.000000
mean     1238.518500     0.4950  ...     0.507000     1.500000
std       439.418206     0.5001  ...     0.500076     1.118314
min       501.000000     0.0000  ...     0.000000     0.000000
25%       851.750000     0.0000  ...     0.000000     0.750000
50%      1226.000000     0.0000  ...     1.000000     1.500000
75%      1615.250000     1.0000  ...     1.000000     2.250000
max      1998.000000     1.0000  ...     1.000000     3.000000

[8 rows x 21 columns]

In [5]:
dataset.isnull()

battery_power   blue  clock_speed  ...  touch_screen   wifi  price_range
0             False  False        False  ...         False  False        False
1             False  False        False  ...         False  False        False
2             False  False        False  ...         False  False        False
3             False  False        False  ...         False  False        False
4             False  False        False  ...         False  False        False
...             ...    ...          ...  ...           ...    ...          ...
1995          False  False        False  ...         False  False        False
1996          False  False        False  ...         False  False        False
1997          False  False        False  ...         False  False        False
1998          False  False        False  ...         False  False        False
1999          False  False        False  ...         False  False        False

[2000 rows x 21 columns]

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [7]:
print(X)

[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 ...
 [1.911e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.512e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 1.000e+00]
 [5.100e+02 1.000e+00 2.000e+00 ... 1.000e+00 1.000e+00 1.000e+00]]


In [8]:
print(y)

[1 2 2 ... 3 0 3]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=35, metric = 'minkowski', p=2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=35, p=2,
                     weights='uniform')

In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [0 0]
 [2 2]
 [1 2]
 [1 2]
 [0 0]
 [0 0]
 [2 3]
 [3 3]
 [2 1]
 [1 1]
 [3 3]
 [1 0]
 [2 2]
 [2 3]
 [2 0]
 [3 3]
 [2 2]
 [1 2]
 [0 1]
 [1 0]
 [0 0]
 [3 3]
 [2 1]
 [1 2]
 [2 2]
 [3 3]
 [2 1]
 [2 3]
 [0 1]
 [1 1]
 [0 0]
 [1 2]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [1 0]
 [2 3]
 [3 3]
 [2 3]
 [2 1]
 [3 3]
 [2 3]
 [0 1]
 [3 3]
 [1 0]
 [2 1]
 [2 3]
 [1 1]
 [1 1]
 [2 3]
 [0 0]
 [2 3]
 [0 0]
 [2 3]
 [2 2]
 [2 2]
 [0 0]
 [2 3]
 [2 3]
 [2 1]
 [1 3]
 [2 2]
 [2 1]
 [2 2]
 [2 3]
 [2 2]
 [2 2]
 [1 2]
 [3 3]
 [2 2]
 [1 1]
 [0 0]
 [2 1]
 [2 3]
 [2 2]
 [2 2]
 [2 1]
 [1 2]
 [2 3]
 [3 3]
 [2 3]
 [0 0]
 [1 0]
 [0 0]
 [2 2]
 [1 1]
 [1 2]
 [3 3]
 [1 1]
 [2 2]
 [1 2]
 [0 1]
 [2 0]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [3 3]
 [0 1]
 [2 1]
 [2 2]
 [1 1]
 [3 3]
 [2 2]
 [2 2]
 [2 3]
 [1 2]
 [3 3]
 [2 3]
 [0 0]
 [0 0]
 [0 1]
 [1 3]
 [2 3]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [3 3]
 [2 2]
 [2 2]
 [0 1]
 [2 1]
 [0 1]
 [0 1]
 [0 0]
 [3 2]
 [0 1]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 2]
 [0 0]
 [1 1]
 [0 1]
 [2 2]
 [1 1]

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[75 17  3  0]
 [26 42 24  0]
 [ 1 34 59  5]
 [ 0  2 37 75]]


0.6275